name: Version Bump

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      custom_version:
        description: 'Custom version (leave empty to use version_type)'
        required: false
        type: string

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Install dependencies
        run: npm install

      - name: Bump version (custom)
        if: ${{ inputs.custom_version != '' }}
        run: npm version ${{ inputs.custom_version }} -m "Bump version to %s"

      - name: Bump version (type)
        if: ${{ inputs.custom_version == '' }}
        run: npm version ${{ inputs.version_type }} -m "Bump version to %s"

      - name: Push changes
        run: git push --follow-tags